### ISSUE TITLE
Data Cleaning and Preprocessing

### ISSUE THREAD

**Issue by skoc** [CBIIT/NCI-DOE-Collab-Pilot1-Tumor_Classifier#6]
Hi all,

thank your for the tool! We want to test the tool with our data, we just want to ask how did you preprocess the raw input data for the model? It will be great if you can share the script or briefly mentioning steps will be helpful as well.

Thanks

**Comment by georgezakinih** [comment]
Thanks for your interest. 

You can either convert the FPKM-UQ values to TPM, or do not do scaling.

Here is a good example for the data processing: 
https://github.com/CBIIT/NCI-DOE-Collab-Pilot1-Tumor_Classifier-hardening/blob/master/TC1-dataprep.ipynb

Best regards,
George.
