### ISSUE TITLE
AttributeError: module 'tensorboard' has no attribute 'lazy'

### ISSUE THREAD

**Issue by ulloaa** [CBIIT/NCI-DOE-Collab-Pilot1-Tumor_Classifier#7]
Hello, 

When I build the environment using the environment.yml provided I get the following error:

AttributeError: module 'tensorboard' has no attribute 'lazy'

Any advice on how to fix this?

I am building on CentOS.

Thanks.

**Comment by jonesse3** [comment]
Hi @ulloaa, I did not get this error when building the environment on NIH's Biowulf using the instructions [here](https://github.com/CBIIT/NCI-DOE-Collab-Pilot1-Tumor-Classifier/blob/master/Pilot1/TC1/README.md). I was able to get the model to train successfully. I was also able to get the model to run on an AWS image of CentOS ~ [CENTOS 8 Desktop - NICE D](https://aws.amazon.com/marketplace/pp/prodview-lqsxon7ifvp2o) with Anaconda3-2022.10-Linux-x86_64 installed. Let us know if you need further assistance with this issue, and we can reopen this issue.
